/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        'hubbl-brand-greige': '#c2bab0',
        'hubbl-brand-greige-dark': '#6A6761',
        'hubbl-brand-red': '#F05A4F',
        'hubbl-brand-red-dark': '#B7281F',
        'hubbl-brand-yellow-vibrant': '#FBF3E0FF',
        'hubbl-brand-yellow': '#F3E559',
        'hubbl-brand-canary': '#E5C03D',
        'hubbl-brand-yellow-dark': '#EED601',
        'hubbl-brand-off-white': '#F7F6F1',
        'hubbl-brand-soft-black': '#262626',
        'hubbl-brand-grey-1': '#e4e3df',
        'hubbl-brand-grey-2': '#9E9B98',
        'hubbl-brand-grey-3': '#4C4B49',
        'hubbl-brand-grey-4': '#323232',
        'hubbl-brand-secondary-green': '#90A510',
        'hubbl-brand-secondary-blue': '#0F7C93',
        'hubbl-header-background': '#F7F6F1',
        'hubbl-footer-background': '#F3F2F2',
        'hubbl-brand-disabled-color': '#DDDBDA',
        'hubbl-brand-divider-color': '#DDDBDA',
        'hubbl-button-brand-color-brackground': '#EEC83F',
        'hubbl-button-brand-color-brackground-active': '#E5C03D',
        'hubbl-button-neutral-color-border': '#EEC83F',
        'hubbl-button-neutral-color-brackground-active': '#E5C03D',
        'hubbl-brand-error-color': '#B7281F',
        'hubbl-brand-warning-color': '#F09033',
        'hubbl-brand-success-color': '#90A510',
        'hubbl-brand-info-color': '#9E9B98',
        'hubbl-dashboard-height': '1000px',
        'hubbl-black-10': '#0000001A',
        'hubbl-brand-logo-red': '#F15A4F',
      },
    },
  },
  plugins: [],
};
